config/routes.rb
Rails.application.routes.draw do
  scope module: :front do
    resources :users, only: [:create, :destroy] do
      resources :logs, only: [:create]
    end
    resources :sessions, only: [:create]
    get 'sign_up', to: 'users#new'
    get 'sign_in', to: 'sessions#new'
    delete 'sign_out', to: 'sessions#destroy'
    root to: 'pages#home'
  end
  namespace :admin do
    resources :users, only: [:index, :show] do
      resources :logs, only: [:index]
    end
    root to: 'users#index'
  end
end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :customer
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  has_many :logs, dependent: :destroy
  validates :name, presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/admin/logs_controller.rb
class Admin::LogsController < AdminController
  def index
    @logs = Log.where(user_id: params[:user_id])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/front/logs_controller.rb
class Front::LogsController < FrontController
  def create
    log = Log.new(params.permit(:user_id))
    log.time = Time.zone.now
    if params[:'start-end'] == 'start'
      log.start_end = 'start'
      if log.save
        redirect_to root_path, notice: '勉強スタート！'
      else
        #
      end
    else
      log.start_end = 'end'
      if log.save
        redirect_to root_path, notice: '勉強終了！'
      else
        #
      end
    end
  end
end

app/controllers/front/pages_controller.rb
class Front::PagesController < FrontController
  def home
    if session[:user_id]
      @user = User.find(session[:user_id])
    else
      redirect_to sign_in_path
    end
  end
end

app/controllers/front/sessions_controller.rb
class Front::SessionsController < FrontController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now[:danger] = 'メールアドレスかパスワードが正しくありません'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/front/users_controller.rb
class Front::UsersController < FrontController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      redirect_to root_path
    else
      #flash.now[:alert] = 'ユーザー名と'
      render 'new'
    end
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/controllers/front_controller.rb
class FrontController < ApplicationController
  layout 'front'
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type
    when 'success'
      'alert-success'
    when 'error'
      'alert-danger'
    when 'alert'
      'alert-warning'
    when 'notice'
      'alert-info'
    else
      flash_type.to_s
    end
  end
end

app/views/admin/logs/index.html.slim
h1 勉強ログ
table.table
  thead
    tr
      th Start or End
      th Time
  tbody
    - @logs.each do |log|
      tr
        th = log.start_end
        th = log.time

app/views/admin/users/index.html.slim
h1 ユーザーの一覧
table.table.table-hover
  thead
    tr
      th ユーザー名
      th メールアドレス
  tbody
    - @users.each do |user|
      tr
        th
          = link_to admin_user_path(user.id)
            = user.name
        th = user.email

app/views/admin/users/show.html.slim
h1 = @user.name
= link_to '勉強ログを確認', admin_user_logs_path(@user.id)

app/views/front/pages/home.html.slim
h1 = @user.name
.form-group
  = link_to '勉強を始める', user_logs_path(@user.id, :'start-end' => 'start'), method: :post, class: 'btn btn-default', :'data-start-end' => 'start'
.form-group
  = link_to '勉強を終わる', user_logs_path(@user.id, :'start-end' => 'end'), method: :post, class: 'btn btn-default', :'data-start-end' => 'end'

app/views/front/users/create.html.slim
h1 Front::Users#create
p Find me in app/views/front/users/create.html.slim

app/views/front/users/destroy.html.slim
h1 Front::Users#destroy
p Find me in app/views/front/users/destroy.html.slim

app/views/front/users/new.html.slim
h1 Sign up
= form_for @user do |f|
  .form-group
    = f.label :name, 'ユーザー名'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード確保'
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit '新規登録', class: 'btn btn-primary'

app/views/layouts/admin.html.slim
doctype html
html
head
  title Mocchi
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
body
.container
  = yield

app/views/layouts/application.html.slim
doctype html
html
head
  title Mocchi
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
body
.container
  = yield

app/views/layouts/front.html.slim
doctype html
html
head
  title Mocchi
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
body
  = render 'shared/header'
  .container
    - flash.each do |type, message|
      div class="alert #{bootstrap_class_for(type)} fade-in"
        /button.close data-dismiss='alert'
          |×
        = message
    = yield

app/views/shared/_header.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      = link_to 'Mocchi', root_path, class: 'navbar-brand'
    ul.nav.navbar-nav.navbar-right
      - if session[:user_id]
        li = link_to 'ログアウト', sign_out_path, method: :delete
      - else
        li = link_to 'ログイン', sign_in_path